import '@testing-library/jest-dom';

// Mock fetch for tests
Object.defineProperty(globalThis, 'fetch', {
  value: jest.fn(),
  writable: true,
});

// Simple Canvas mock for PixiJS tests
(HTMLCanvasElement.prototype as any).getContext = jest.fn(() => ({
  fillStyle: '',
  strokeStyle: '',
  lineWidth: 1,
  fillRect: jest.fn(),
  strokeRect: jest.fn(),
  clearRect: jest.fn(),
  getImageData: jest.fn(() => ({ data: new Array(4) })),
  putImageData: jest.fn(),
  createImageData: jest.fn(() => ({ data: new Array(4) })),
  setTransform: jest.fn(),
  drawImage: jest.fn(),
  save: jest.fn(),
  restore: jest.fn(),
  beginPath: jest.fn(),
  moveTo: jest.fn(),
  lineTo: jest.fn(),
  closePath: jest.fn(),
  stroke: jest.fn(),
  translate: jest.fn(),
  scale: jest.fn(),
  rotate: jest.fn(),
  arc: jest.fn(),
  fill: jest.fn(),
  measureText: jest.fn(() => ({ width: 0 })),
  transform: jest.fn(),
  rect: jest.fn(),
  clip: jest.fn(),
  canvas: document.createElement('canvas'),
  drawingBufferWidth: 800,
  drawingBufferHeight: 600,
  getExtension: jest.fn(),
  getParameter: jest.fn(),
  createShader: jest.fn(),
  shaderSource: jest.fn(),
  compileShader: jest.fn(),
  createProgram: jest.fn(),
  attachShader: jest.fn(),
  linkProgram: jest.fn(),
  useProgram: jest.fn(),
  createBuffer: jest.fn(),
  bindBuffer: jest.fn(),
  bufferData: jest.fn(),
  enableVertexAttribArray: jest.fn(),
  vertexAttribPointer: jest.fn(),
  uniform1f: jest.fn(),
  uniform2f: jest.fn(),
  uniform3f: jest.fn(),
  uniform4f: jest.fn(),
  uniformMatrix4fv: jest.fn(),
  createTexture: jest.fn(),
  bindTexture: jest.fn(),
  texImage2D: jest.fn(),
  texParameteri: jest.fn(),
  generateMipmap: jest.fn(),
  blendFunc: jest.fn(),
  enable: jest.fn(),
  disable: jest.fn(),
  depthFunc: jest.fn(),
  clear: jest.fn(),
  clearColor: jest.fn(),
  clearDepth: jest.fn(),
  viewport: jest.fn(),
  drawArrays: jest.fn(),
  drawElements: jest.fn(),
  finish: jest.fn(),
  flush: jest.fn(),
  getShaderParameter: jest.fn(() => true),
  getProgramParameter: jest.fn(() => true),
  getShaderInfoLog: jest.fn(() => ''),
  getProgramInfoLog: jest.fn(() => ''),
}));

// Mock PixiJS
jest.mock('pixi.js', () => ({
  Application: jest.fn(() => ({
    stage: {
      addChild: jest.fn(),
      removeChild: jest.fn(),
      on: jest.fn(),
      off: jest.fn(),
      emit: jest.fn(),
      position: { x: 0, y: 0 },
      scale: { x: 1, y: 1 },
    },
    renderer: {
      resize: jest.fn(),
    },
    view: {
      canvas: document.createElement('canvas'),
    },
    destroy: jest.fn(),
  })),
  Container: jest.fn(() => ({
    addChild: jest.fn(),
    removeChild: jest.fn(),
    on: jest.fn(),
    off: jest.fn(),
    emit: jest.fn(),
    position: { x: 0, y: 0 },
    scale: { x: 1, y: 1 },
  })),
  Texture: {
    from: jest.fn(() => ({
      width: 24,
      height: 24,
    })),
    WHITE: {},
  },
  Sprite: jest.fn(() => ({
    anchor: { set: jest.fn() },
    position: { x: 0, y: 0 },
    scale: { x: 1, y: 1 },
  })),
  Graphics: jest.fn(() => ({
    beginFill: jest.fn().mockReturnThis(),
    drawRect: jest.fn().mockReturnThis(),
    endFill: jest.fn().mockReturnThis(),
    clear: jest.fn().mockReturnThis(),
  })),
}));